### ISSUE TITLE
Review: ViewBill.jsx and CreateEmail.jsx

### ISSUE THREAD

**Issue by ethancheez** [hidoe-legistracker/hidoe-legistracker#89]
## Overview

The focus for this code review will be centered around the ViewBill and CreateEmail pages.    

## Review Branch

[review-2](https://github.com/hidoe-legistracker/hidoe-legistracker/tree/review-2)

## Files to review

* [ViewBill.jsx](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-2/app/imports/ui/pages/ViewBill.jsx)
* [CreateEmail.jsx](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-2/app/imports/ui/pages/CreateEmail.jsx)

## Checklists

* [Architecture](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/architecture-checklist.md)
* [Design](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/design-checklist.md)
* [JS](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/js-checklist.md)
* [React](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/react-checklist.md)

## Due date

9/20/2022

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by ethancheez** [comment]
## ViewBill.jsx:

L5, 6, 15-30: Get rid of “stuff”.

L12-32: DE-04: Eliminate large comment block

L35-147: DE-06: Adding some comments and/or empty lines to separate sections of the ViewBill page would be nice to read and identify sections.

## CreateEmail.jsx:

L39: JS-06: Remove console.log

L42: DE-03: Eliminate dead code in comment

**Comment by ecadiena** [comment]
## ViewBill.jsx
DE-04, DE-05, JS-07: Remove large code blocks (L4-7, L12-32)

## CreateEmail.jsx
DE-05: Remove comment (L42, L30)
RE-01: Unnecessary <Container> ? (L85, L87)
JS-06: Remove console.log (L39)

**Comment by ColeAmparo** [comment]
## ViewBill.jsx

L12-32: DE-04 - Delete large blocks of commented-out code. Commented-out code also contains references to the unused “Stuff” collection. 

L35, L149-165: DE-01 - Is it possible to refactor this code so instead of having two containers in each other, the notification button is just in a row like the other components on the page? The two containers seem unnecessary but let me know if there is a reason. 


## CreateEmail.jsx

L64-66, L85-77: DE-01 - I am assuming the 
 ``` <hr /> ```

is in a container because of the margin, would it be better to refactor it to 

```<hr className=”m-2” /> ```? 

It saves 2 lines but if we want to go for the container for a more uniform margin across the page it might be better. 

L39: JS-06 - Console.log not removed.

**Comment by larissa-tsai** [comment]
### ViewBill.jsx
DE-03/04/05, JS-07: 
- (L12-32) Comment still refers to Stuff and Stuff documents, and is a large code block
- (L4-7) comments are starting with '//' but also needs to be removed because it is dead code/not relevant

### CreateEmail.jsx
DE-03/04/05: Make new line for code(L41), Dead code (L42)
JS-06: avoid using console log
ES-01: Eslint console log error
DE-01/RE-01: Simplify code/refactor? (L85-87)

**Comment by adamjparrilla** [comment]
### ViewBill.jsx:
L4-L7, DE-05: Delete commented out unused imports
L12-L32, DE-04: Delete the large amount of commented out code 

### CreateEmail.jsx: 
L42, DE-03: Remove commented out code
L39, JS-06: Avoid console.log

**Comment by ianbm** [comment]
### ViewBill.jsx
Lines 53-117: "style={{ fontWeight: 'bold' }}" is repeated more than twice
Lines 4-7, 12-32: remove comments

### CreateEmail.jsx
Line 42: remove comment
Line 39: remove console.log
